format = """$os$directory$git_branch$rust$golang$character"""

command_timeout = 500

[os]
disabled = false
format = "[$symbol ]($style)"
style = "bold blue"

[os.symbols]
Ubuntu = ""

[username]
show_always = true
format = "[$user]($style) "
style_user = "bold blue"

[directory]
style = "bold cyan"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "fg:#000000 bg:#ffff00 bold"
format = "[ $symbol$branch ]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
